module.exports = [
  {
    id: 14,
    first_name: "Rebecca",
    last_name: "Collins",
    age: "29",
    height: `5'5`,
    jersey: "1",
    description: `Has played on the team for over 10 years, she will play her heart out for 5 minutes and then need a sub. She's also A player that can dominate the midfield position while dangling the ball around players to make a game winning play.`,
    position: "Midfield",
    img: "http://localhost:8080/images/rebecca.png",
  },
  {
    id: 13,
    first_name: "Olivia",
    last_name: "Collins",
    age: "25",
    height: `5'5`,
    jersey: "2",
    description:
      "Has played on the team for 5 years and is an amazing goal keeper because when she was younger her older sisters would fire shots at her all day long!",
    position: "Goalie/ Defence",
    img: "http://localhost:8080/images/olivia.png",
  },
  {
    id: 12,
    first_name: "Katy",
    last_name: "Gilmour",
    age: "31",
    height: `5'5`,
    jersey: "4",
    description:
      "Katy has been an integral part of the team for the past two years, and during that time, she has developed a shot that strikes fear into the hearts of her opponents. No one wants to be on the receiving end",
    position: "C - Midfeild",
    img: "http://localhost:8080/images/katy.png",
  },
  {
    id: 10,
    first_name: "Natasha",
    last_name: "Nagra",
    age: "28",
    height: `5'3`,
    jersey: "5",
    description:
      "Tash has played on the team for 6 years and shes a lightening bolt who never gives up!",
    position: "Midfield",
    img: "http://localhost:8080/images/tash.png",
  },
  {
    id: 9,
    first_name: "Heavenly",
    last_name: "Brock",
    age: "25",
    height: `5'5`,
    jersey: "7",
    description:
      "Heav - has played on the team for 5 years and always our last women back. She isn’t afraid to bark orders at her team mates when they step out of line. The opposing team needs to watch out for her sneaky hip checks.",
    position: "Sweeper",
    img: "http://localhost:8080/images/heav.png",
  },
  {
    id: 8,
    first_name: "Sarah",
    last_name: "Rust",
    age: "20",
    height: `5'7`,
    jersey: "10",
    description:
      "Sarah - is one of the youngest players on the team and is the number one professional corner taker, her kicks are perfect but the teams finishing is not.",
    position: "Defence",
    img: "http://localhost:8080/images/sarahR.png",
  },
  {
    id: 7,
    first_name: "Erica",
    last_name: "Foulds",
    age: "30",
    height: `5'4`,
    jersey: "11",
    description:
      "Erica she will come out of no where and take a beating for her team. You can always count on her.",
    position: "Defence",
    img: "http://localhost:8080/images/erica.png",
  },
  {
    id: 5,
    first_name: "Christina",
    last_name: "Klemencic",
    age: "39",
    height: `6'3`,
    jersey: "14",
    description:
      "Beela is the captain and has played on the team for over 15 years and is the longest standing team mate she is always cheering the team on and making everyone laugh while holding down the back line like a brick wall. ",
    position: "Defence",
    img: "http://localhost:8080/images/beela.png",
  },
  {
    id: 3,
    first_name: "Natasha",
    last_name: "Collins",
    age: "29",
    height: `5'4`,
    jersey: "18",
    description: `Nat has played on the team for over 10 years and is our star Forward, she's always getting her self into position to score those game winning goals `,
    position: "Forward",
    img: "http://localhost:8080/images/nat.png",
  },
  {
    id: 2,
    first_name: "Trish",
    last_name: "Leggett",
    age: "39",
    height: `5'4`,
    jersey: "19",
    description:
      "Trish has played on the team for over 10 years and is the centre mid toughie. She never gives up no matter how many balls she gets to the face or yellow cards",
    position: "Center Midfield",
    img: "http://localhost:8080/images/trish.png",
  },
];
