module.exports = [
  {
    id: 7548757693930304,
    first_name: "Rebecca",
    last_name: "Collins",
    age: "29",
    height: `5'5`,
    jersey: "1",
    description:
      "Has played on the team for over 10 years, and will continue until her knees give out",
    position: "Midfield",
    img:"http://localhost:2020/images/rebecca.png",
  },
  {
    id: 20985648387542,
    first_name: "Olivia",
    last_name: "Collins",
    age: "25",
    height: `5'5`,
    jersey: "2",
    description:
      "Has played on the team for 5 years and she loves to yelland tell the team what to MOVE UP!!",
    position: "Defence",
    img:"http://localhost:2020/images/olivia.png",
  },
  // {
  //   id: 234342342342343,
  //   first_name: "Christina",
  //   last_name: "Renneberg",
  //   age: "35",
  //   height: `5'3`,
  //   jersey: "3",
  //   description: "Has played on the team for 15 years.",
  //   position: "Midfield",
  //   img:"http://localhost:2020/images/generic-dog.png",
  // },
  {
    id: 66456787855444,
    first_name: "Katy",
    last_name: "Collins-Gilmour",
    age: "31",
    height: `5'5`,
    jersey: "4",
    description:
      "Katy has played on the team for 1 year and everyone is scared of her shot!",
    position: "Center Midfeild",
    img:"http://localhost:2020/images/katy.png",
  },
  {
    id: 5674646744675,
    first_name: "Natasha",
    last_name: "Nagra",
    age: "28",
    height: `5'3`,
    jersey: "5",
    description:
      "Tash has played on the team for 6 years and she is so fast no one can catch her!",
    position: "Midfield",
    img:"http://localhost:2020/images/tash.png",
  },
  // {
  //   id: 467674678798926,
  //   first_name: "Alyssa",
  //   last_name: "Spencer",
  //   age: "31",
  //   height: `5'5`,
  //   jersey: "6",
  //   description:
  //     "Alyssa has played on the team for 2 years and she loves to get called for `cleat on foot`",
  //   position: "Defence",
  //   img:"http://localhost:2020/images/generic-dog3.png",
  // },
  {
    id: 7345454525565575,
    first_name: "Heavenly",
    last_name: "Brock",
    age: "25",
    height: `5'5`,
    jersey: "7",
    description:
      "Heav has played on the team for 5 years and she is a killer sweeper",
    position: "Sweeper",
    img:"http://localhost:2020/images/heav.png",
  },
  // {
  //   id: 856365636346356,
  //   first_name: "Caitlynn",
  //   last_name: "Salsman",
  //   age: "25",
  //   height: `5:6`,
  //   jersey: "9",
  //   description:
  //     "Caitlynn has played on the team for 5 years and she is a the best midfielder",
  //   position: "Midfield",
  //   img:"http://localhost:2020/images/generic-dog-2.png",
  // },
  {
    id: 935464768968,
    first_name: "Sarah",
    last_name: "Rust",
    age: "20",
    height: `5'7`,
    jersey: "10",
    description:
      "Sarah has played on the team for 2 years and she is an amazing defender",
    position: "Defence",
    img:"http://localhost:2020/images/sarahR.png",
  },
  {
    id: 1084508208245702,
    first_name: "Erica",
    last_name: "Foulds",
    age: "30",
    height: `5'4`,
    jersey: "11",
    description: "Erica has been on the team for over 10 years",
    position: "Defence",
    img:"http://localhost:2020/images/erica.png",
  },
  // {
  //   id: 1152857408430327,
  //   first_name: "Linda",
  //   last_name: "Jones",
  //   age: "35",
  //   height: `5'5`,
  //   jersey: "12",
  //   description:
  //     "Linda has played on the team for 10 years, she owns 5 differnt types of boots but prefers her 10 years old ones",
  //   position: "Center Midfield",
  //   img:"http://localhost:2020/images/generic-dog.png",
  // },
  // {
  //   id: 124582704582352,
  //   first_name: "Monica",
  //   last_name: "Ciolfi",
  //   age: "35",
  //   height: `5'3`,
  //   jersey: "13",
  //   description:
  //     "Moncia has played with the team for 5 years and is a beast at trapping the ball",
  //   position: "Defence",
  //   img:"http://localhost:2020/images/generic-dog3.png",
  // },
  {
    id: 184750284524523,
    first_name: "Christina",
    last_name: "Klemencic",
    age: "39",
    height: `6'3`,
    jersey: "14",
    description:
      "Beela has played on the team for over 15 years and she is the most amazing captain and defender",
    position:"Defence",
    img:"http://localhost:2020/images/beela.png",
  },
  {
    id: 1434058204592245,
    first_name: "Rebeccah",
    last_name: "Stefina",
    age: "30",
    height: `5'6`,
    jersey: "15",
    description: "Rebeccah has played on the team for 8 years and",
    position: "Forward",
    img:"http://localhost:2020/images/rebeccah.png",
  },
  // {
  //   id: 1545229485723495,
  //   first_name: "Jennika",
  //   last_name: "Mercer",
  //   age: "20",
  //   height: `5'7`,
  //   jersey: "16",
  //   description: "Jennika has played on the team for 2 years and",
  //   position: "Midfield",
  //   img:"http://localhost:2020/images/generic-dog-2.png",
  // },
  {
    id: 1485209457024856,
    first_name: "Kamryn",
    last_name: "McKean",
    age: "20",
    height: `5'4`,
    jersey: "17",
    description: "Kam has played on the team for 2 years",
    position: "Midfield",
    img:"http://localhost:2020/images/kam.png",
  },
  {
    id: 14350987437507,
    first_name: "Natasha",
    last_name: "Collins",
    age: "29",
    height: `5'4`,
    jersey: "18",
    description:
      "Nat has played on the team for over 10 years and is the top scorer on the team",
    position: "Forward",
    img:"http://localhost:2020/images/nat.png",
  },
  {
    id: 1824509824705828,
    first_name:"Trish",
    last_name:"Leggett",
    age:"39",
    height:`5'4`,
    jersey:"19",
    description:"Trish has played on the team for over 10 years and ",
    position: "Center Midfield",
    img:"http://localhost:2020/images/trish.png",
  },
  // {
  //   id: 13450834587839,
  //   first_name:"Brittany",
  //   last_name:"Salmon",
  //   age:"32",
  //   height:`6'1`,
  //   jersey:"19",
  //   description:
  //     "Brittany has played on team for 2 years and she is so tall no one can cover her and she scores with her head all the time",
  //   position:"Center Midfield",
  //   img:"http://localhost:2020/images/generic-dog3.png",
  // },
  // {
  //   id: 245824057257250,
  //   first_name:"Caroline",
  //   last_name:"Mimnaugh",
  //   age:"45",
  //   height:`6'1`,
  //   jersey:"33",
  //   description:"Caraoline has played on the team for over 15 years and the team calls her mouse because of the noises she makes when trying to get the ball",
  //   position:"Midfield",
  //   img:"http://localhost:2020/images/generic-dog.png",
  // },
  {
    id: 23485702870251,
    first_name:"Joy",
    last_name:"Braun",
    age:"38",
    height:`5'`,
    jersey:"0",
    description:"Joy has played on the team for 5 years and she is the best goalie in the league ",
    position:"Goalie",
    img:"http://localhost:2020/images/joy.png",
  },
  {
    id: 485242348752,
    first_name: "Sarah",
    last_name: "Bryson",
    age: "37",
    height: `5'5`,
    jersey: "",
    description: "Sarah has been the coach for 2 years...",
    position: "Coach",
    img:"http://localhost:2020/images/coach.png",
  },
];
